### ISSUE TITLE
MongoDB connection sharing

### ISSUE THREAD

**Issue by antonmoiseev** [zeit/vrs#2]
👋Hi! Spent most of the yesterday figuring out how to properly connect to MongoDB Atlas from the serverless environment and overnight you are releasing this comprehensive store project! So I have a couple of specific questions.

1. Have you considered sharing MongoDB connection between multiple invocations? It looks like MongoDB folks [recommend](https://www.mongodb.com/blog/post/serverless-development-with-nodejs-aws-lambda-mongodb-atlas) declaring it as a global variable, so it may survive multiple invocations of a single lambda instance.

2. They also [mention](https://www.mongodb.com/blog/post/optimizing-aws-lambda-performance-with-mongodb-atlas-and-nodejs) that for performance it's critical to set `callbackWaitsForEmptyEventLoop` context's property to `false` which helps "avoiding closing the database connection". It's a AWS Lambda-specific [setting](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html), which tight to how AWS Lambda freezes processes. I believe otherwise AWS Lambda doesn't send the response to the user and waits till the connection is closed. This probably is not applicable to Now, since in Now we can directly write into HTTP response, rather than dealing with event callbacks, but still I would love if you could confirm and dispel any doubts?

**Comment by yann-yinn** [comment]
@antonmoiseev above recommendations allow to share a single db connection for multiple invocations of *one single* lambda while container is alive (which is already a huuuge improvement), right ?
But if you have 1000 lambdas, you have 1000 connections to your database, and there is no way to avoid with lambdas, am i correct ? This does not sounds good for perf on Mongodb side ... (CPU and memory usage for authentication on each connection)

**Comment by antonmoiseev** [comment]
> above recommendations allow to share a single db connection for multiple invocations of _one single lambda container_ while container is alive (which is already a huuuge improvement), right ?

Correct.

> But if you have 1000 lambdas, you have 1000 connections to your database, and there is no way to avoid this with lambdas, am i correct ? This does not sounds good for perf on Mongodb side ... (CPU and memory usage for authentication on each connection)

I don't think it's a MongoDB-specific problem, and it's probably a good sign if your project needs to deal with this kind of challenges :wink:. But [according to the docs](https://docs.atlas.mongodb.com/connection-limits/) MongoDB Atlas is capable of handling up to 128000 concurrent connections which reserves plenty of room to grow.

**Comment by coetry** [comment]
The great thing about SPR (`stale-while-revalidate`) is that lambda responses are cached on our edge, so the database is not hit very frequently and reusing DB connections between invocations is not necessary 😌. The user is *always* served data from the cache, so ensuring that we have a fresh connection each time the cache is validated in the background is solid. Hope that clarifies! Will close this issue!

**Comment by styfle** [comment]
@antonmoiseev Number 2, `callbackWaitsForEmptyEventLoop ` was implemented in https://github.com/zeit/now-builders/pull/505

You can try it out with `@now/node@canary`
