### ISSUE TITLE
now 15.3.0 issues, now secrets

### ISSUE THREAD

**Issue by moflo** [zeit/vrs#5]
Two separate issues, but first the README may need to be updated due to errors adding  secrets with now v15.3.0. The work around is to remove the "@" character, or use the `.env` file method:

```
$>now --version
15.3.0

$>now secret add @vrs-github-client-id "GITHUBTEST1"
> Error! Only alphanumerics and `/ . _ -` are allowed as `name`

$> now secret add vrs-github-client-id "GITHUBTEST1"
> Success! Secret vrs-github-client-id added (moflo) [125ms]
```

**Comment by TooTallNate** [comment]
Thanks for the report. We've corrected the blog post.
