### ISSUE TITLE
ENV issues

### ISSUE THREAD

**Issue by arulananth** [zeit/vrs#8]
Error! The following env vars are not defined in `.env` file:
  - "GITHUB_CLIENT_ID"
  - "GITHUB_CLIENT_SECRET"
  - "MONGODB_ATLAS_URI"
  - "STRIPE_SECRET"

**Comment by paulogdm** [comment]
To be able to develop locally, you must set those variables like:
// .env
```
GITHUB_CLIENT_ID=123
GITHUB_CLIENT_SECRET=abc
MONGODB_ATLAS_URI=https://aabbcc
STRIPE_SECRET=abc
```

**Comment by arulananth** [comment]
Possible call Local MongDB URL ??

**Comment by paulogdm** [comment]
Sure, if you have a `localhost:XXXX`.
